In [17]:
import pandas as pd
import requests as rq
import numpy as np
from datetime import datetime, timedelta
import os

In [2]:
# Ссылка на данные
url1 = "https://iss.moex.com/iss/analyticalproducts/futoi/securities/si.json?from=2023-11-07&till=2023-11-08&table_type=full"
url2 = "https://iss.moex.com/iss/analyticalproducts/futoi/securities/si.json?from=2023-11-06&till=2023-11-07&table_type=full"

In [3]:
# Отправляем GET-запрос по указанной ссылке
response = rq.get(url1)

# Проверяем статус ответа
if response.status_code == 200:
    # Загружаем данные из ответа в переменную data в случае успеха
    data = response.json()
else:
    print("Ошибка при получении данных")
    

columns = response.json()["futoi"]['columns']

data = response.json()["futoi"]["data"]

df1 = pd.DataFrame(data, columns=columns)


# Отправляем GET-запрос по указанной ссылке
response = rq.get(url2)

# Проверяем статус ответа
if response.status_code == 200:
    # Загружаем данные из ответа в переменную data в случае успеха
    data = response.json()
else:
    print("Ошибка при получении данных")


columns = response.json()["futoi"]['columns']

data = response.json()["futoi"]["data"]

df2 = pd.DataFrame(data, columns=columns)

In [4]:
print(df1.sort_values(by=['ticker', 'tradedate','tradetime']).reset_index().drop('index', axis=1))
print(len(np.array(df1['ticker'])))

     sess_id  seqnum   tradedate tradetime ticker clgroup     pos  pos_long  \
0       6922      59  2023-11-07  09:05:00     Si     FIZ -155138    439394
1       6922      59  2023-11-07  09:05:00     Si     YUR  155138   3192186
2       6922      60  2023-11-07  09:10:00     Si     FIZ -155331    439692
3       6922      60  2023-11-07  09:10:00     Si     YUR  155331   3192080
4       6922      61  2023-11-07  09:15:00     Si     FIZ -155165    439792
..       ...     ...         ...       ...    ...     ...     ...       ...
695     6924      56  2023-11-08  23:40:00     Si     YUR  140369   3221244
696     6924      57  2023-11-08  23:45:00     Si     FIZ -140319    456549
697     6924      57  2023-11-08  23:45:00     Si     YUR  140325   3221244
698     6924      58  2023-11-08  23:50:00     Si     FIZ -140215    455996
699     6924      58  2023-11-08  23:50:00     Si     YUR  140215   3221177

     pos_short  pos_long_num  pos_short_num              systime
0      -594532          7372          13209  2023-11-07 09:05:02
1     -3037048           231            196  2023-11-07 09:05:02
2      -595023          7403          13239  2023-11-07 09:10:06
3     -3036749           233            195  2023-11-07 09:10:06
4      -594957          7415          13266  2023-11-07 09:15:05
..         ...           ...            ...                  ...
695   -3080875           249            182  2023-11-08 23:40:06
696    -596868          7368          13637  2023-11-08 23:45:06
697   -3080919           249            182  2023-11-08 23:45:06
698    -596211          7344          13611  2023-11-08 23:50:07
699   -3080962           249            182  2023-11-08 23:50:07

[700 rows x 12 columns]
700

In [5]:
df2.sort_values(by=['ticker', 'tradedate', 'tradetime']).reset_index().drop('index', axis=1)

,sess_id,seqnum,tradedate,tradetime,ticker,clgroup,pos,pos_long,pos_short,pos_long_num,pos_short_num,systime
0,6921,59,2023-11-06,09:05:00,Si,FIZ,-152370,438179,-590549,7646,12891,2023-11-06 09:05:03
1,6921,59,2023-11-06,09:05:00,Si,YUR,152370,3193000,-3040630,234,188,2023-11-06 09:05:03
2,6921,60,2023-11-06,09:10:00,Si,FIZ,-152566,437884,-590450,7660,12881,2023-11-06 09:10:05
3,6921,60,2023-11-06,09:10:00,Si,YUR,152566,3192851,-3040285,237,185,2023-11-06 09:10:05
4,6921,61,2023-11-06,09:15:00,Si,FIZ,-152331,437356,-589687,7675,12905,2023-11-06 09:15:05
...,...,...,...,...,...,...,...,...,...,...,...,...
695,6923,56,2023-11-07,23:40:00,Si,YUR,117102,3193534,-3076432,241,183,2023-11-07 23:40:06
696,6923,57,2023-11-07,23:45:00,Si,FIZ,-117198,460148,-577346,7857,12383,2023-11-07 23:45:06
697,6923,57,2023-11-07,23:45:00,Si,YUR,117198,3193535,-3076337,242,182,2023-11-07 23:45:06
698,6923,58,2023-11-07,23:50:00,Si,FIZ,-117280,459912,-577192,7844,12367,2023-11-07 23:50:06
699,6923,58,2023-11-07,23:50:00,Si,YUR,117280,3193508,-3076228,241,183,2023-11-07 23:50:06

In [6]:
print(len(np.array(df2['ticker'])))

700

In [7]:
frames = [df1, df2]

result = pd.concat(frames).sort_values(by=['ticker', 'tradedate', 'tradetime']).reset_index().drop('index', axis=1)
filename = "aboba_date.csv"
result.to_csv(filename, sep=',', index=False, encoding='utf-8')

print(result)

print(len(np.array(result['ticker'])))

      sess_id  seqnum   tradedate tradetime ticker clgroup     pos  pos_long  \
0        6921      59  2023-11-06  09:05:00     Si     FIZ -152370    438179
1        6921      59  2023-11-06  09:05:00     Si     YUR  152370   3193000
2        6921      60  2023-11-06  09:10:00     Si     FIZ -152566    437884
3        6921      60  2023-11-06  09:10:00     Si     YUR  152566   3192851
4        6921      61  2023-11-06  09:15:00     Si     FIZ -152331    437356
...       ...     ...         ...       ...    ...     ...     ...       ...
1395     6924      56  2023-11-08  23:40:00     Si     YUR  140369   3221244
1396     6924      57  2023-11-08  23:45:00     Si     FIZ -140319    456549
1397     6924      57  2023-11-08  23:45:00     Si     YUR  140325   3221244
1398     6924      58  2023-11-08  23:50:00     Si     FIZ -140215    455996
1399     6924      58  2023-11-08  23:50:00     Si     YUR  140215   3221177

      pos_short  pos_long_num  pos_short_num              systime
0       -590549          7646          12891  2023-11-06 09:05:03
1      -3040630           234            188  2023-11-06 09:05:03
2       -590450          7660          12881  2023-11-06 09:10:05
3      -3040285           237            185  2023-11-06 09:10:05
4       -589687          7675          12905  2023-11-06 09:15:05
...         ...           ...            ...                  ...
1395   -3080875           249            182  2023-11-08 23:40:06
1396    -596868          7368          13637  2023-11-08 23:45:06
1397   -3080919           249            182  2023-11-08 23:45:06
1398    -596211          7344          13611  2023-11-08 23:50:07
1399   -3080962           249            182  2023-11-08 23:50:07

[1400 rows x 12 columns]
1400

Далее будет пробегать по массиву дат и таким образом сформируем всю таблицу

Ниже я задаю массив всех дат

In [8]:
start_date = datetime(2020, 5, 8)
end_date = datetime.now()

current_date = start_date
array_date = []
while current_date <= end_date:
    array_date += [current_date.strftime("%Y-%m-%d")]
    # print(current_date.strftime("%Y-%m-%d"))
    current_date += timedelta(days=1)
# print(array_date[-13])
# print((datetime.strptime(array_date[-13], '%Y-%m-%d') - timedelta(days=1)).strftime("%Y-%m-%d"))

2023-11-01
2023-10-31

In [ ]:
def add_new_day(date_today: str, df: pd.DataFrame, ticker_name: str):
    date_yesterday = (datetime.strptime(date_today, '%Y-%m-%d') - timedelta(days=1)).strftime("%Y-%m-%d")
    url = f"https://iss.moex.com/iss/analyticalproducts/futoi/securities/{ticker_name}.json?from={date_yesterday}&till={date_today}&table_type=full"

    while True:
        try:
            # Ваш код, который может вызвать ошибку
            response = rq.get(url)
            # break  # Если ошибки не возникло, выходим из цикла
        except Exception as e:
            # Обработка других исключений
            print(f"Произошла ошибка: {e}")
    

    # Проверяем статус ответа
    if response.status_code != 200:
        print("Ошибка при получении данных")
        add_new_day(date_today, df)

    df_for_add = pd.DataFrame(response.json()["futoi"]["data"], columns=response.json()["futoi"]['columns'])
    df_for_add.sort_values(by=['ticker', 'tradedate','tradetime']).reset_index().drop('index', axis=1)
   
    # print(df)
    # print(df_for_add)
    df = pd.concat([df, df_for_add]).sort_values(by=['ticker', 'tradedate', 'tradetime']).reset_index().drop('index', axis=1)
    # print(df)
    return df
    # print(df_for_add)

ticker_names=['si', 'br', 'ri', 'eu', 'mx', 'sr', 'ox', 'gz', 'yn', 'fv', 'vi', 'lk']

for ticker_name in ticker_names:
    if os.path.exists(f"{ticker_name}_full_date.csv"):
        df = pd.read_csv(f"{ticker_name}_full_date.csv")
        last_valid_date_index = df['tradedate'].last_valid_index()
        last_valid_date_value  = df['tradedate'][last_valid_date_index]
        date_tomorrow = (datetime.strptime(last_valid_date_value, '%Y-%m-%d') + timedelta(days=1)).strftime("%Y-%m-%d")
        print(date_tomorrow)
    # Вывод первых нескольких строк DataFrame для проверки
        for date in array_date[array_date.index(date_tomorrow)+1:]:
            df = add_new_day(date, df, ticker_name)
            filename = f"{ticker_name}_full_date.csv"
            df.to_csv(filename, sep=',', index=False, encoding='utf-8')
            print(date)
        print(df)
    else:
        print(f"Файл '{file_path}' не существует.")
        df = pd.DataFrame()
        for date in array_date:
            df = add_new_day(date, df, ticker_name)
            filename = f"{ticker_name}_full_date.csv"
            df.to_csv(filename, sep=',', index=False, encoding='utf-8')
            print(date)
        print(df)

    filename = f"{ticker_name}_full_date.csv"
    df.to_csv(filename, sep=',', index=False, encoding='utf-8')

2023-03-18
2023-03-19
2023-03-20
2023-03-21
2023-03-22
2023-03-23
2023-03-24
2023-03-25
2023-03-26
2023-03-27
2023-03-28
2023-03-29
2023-03-30
2023-03-31
2023-04-01
2023-04-02
2023-04-03
2023-04-04
2023-04-05
2023-04-06
2023-04-07
2023-04-08
2023-04-09
2023-04-10
2023-04-11
2023-04-12
2023-04-13
2023-04-14
2023-04-15
2023-04-16
2023-04-17
2023-04-18
2023-04-19
2023-04-20
2023-04-21
2023-04-22
2023-04-23
2023-04-24
2023-04-25
2023-04-26
2023-04-27
2023-04-28
2023-04-29
2023-04-30
2023-05-01
2023-05-02
2023-05-03
2023-05-04
2023-05-05
2023-05-06
2023-05-07
2023-05-08
2023-05-09
2023-05-10
2023-05-11
2023-05-12
2023-05-13
2023-05-14
2023-05-15
2023-05-16
2023-05-17
2023-05-18
2023-05-19
2023-05-20
2023-05-21
2023-05-22
2023-05-23
2023-05-24
2023-05-25
2023-05-26
2023-05-27
2023-05-28
2023-05-29
2023-05-30
2023-05-31
2023-06-01
2023-06-02
2023-06-03
2023-06-04
2023-06-05
2023-06-06
2023-06-07
2023-06-08
2023-06-09
2023-06-10
2023-06-11
2023-06-12
2023-06-13
2023-06-14
2023-06-15
2023-06-16
2023-06-17
2023-06-18
2023-06-19
2023-06-20
2023-06-21
2023-06-22
2023-06-23
2023-06-24
2023-06-25
2023-06-26
2023-06-27
2023-06-28
2023-06-29
2023-06-30
2023-07-01
2023-07-02
2023-07-03
2023-07-04
2023-07-05
2023-07-06
2023-07-07
2023-07-08
2023-07-09
2023-07-10
2023-07-11
2023-07-12
2023-07-13
2023-07-14
2023-07-15
2023-07-16
2023-07-17
2023-07-18
2023-07-19
2023-07-20
2023-07-21
2023-07-22
2023-07-23
2023-07-24
2023-07-25
2023-07-26
2023-07-27
2023-07-28
2023-07-29
2023-07-30
2023-07-31
2023-08-01
2023-08-02
2023-08-03
2023-08-04
2023-08-05
2023-08-06
2023-08-07
2023-08-08
2023-08-09
2023-08-10
2023-08-11
2023-08-12
2023-08-13
2023-08-14
2023-08-15
2023-08-16
2023-08-17
2023-08-18
2023-08-19
2023-08-20
2023-08-21
2023-08-22
2023-08-23
2023-08-24
2023-08-25
2023-08-26
2023-08-27
2023-08-28
2023-08-29
2023-08-30
2023-08-31
2023-09-01
2023-09-02
2023-09-03
2023-09-04
2023-09-05
2023-09-06
2023-09-07
2023-09-08
2023-09-09
2023-09-10
2023-09-11
2023-09-12
2023-09-13
2023-09-14
2023-09-15
2023-09-16
2023-09-17
2023-09-18
2023-09-19
2023-09-20
2023-09-21
2023-09-22
2023-09-23
2023-09-24
2023-09-25
2023-09-26
2023-09-27
2023-09-28
2023-09-29
2023-09-30
2023-10-01
2023-10-02
2023-10-03
2023-10-04
2023-10-05
2023-10-06
2023-10-07
2023-10-08
2023-10-09
2023-10-10
2023-10-11
2023-10-12
2023-10-13
2023-10-14
2023-10-15
2023-10-16
2023-10-17
2023-10-18
2023-10-19
2023-10-20
2023-10-21
2023-10-22
2023-10-23
2023-10-24
2023-10-25
2023-10-26
2023-10-27
2023-10-28
2023-10-29
2023-10-30
2023-10-31
2023-11-01
2023-11-02
2023-11-03
2023-11-04
2023-11-05
2023-11-06
2023-11-07
2023-11-08
2023-11-09
2023-11-10
2023-11-11
2023-11-12
2023-11-13
       sess_id seqnum   tradedate tradetime ticker clgroup      pos pos_long  \
0         6035     66  2020-05-08  10:02:14     Si     FIZ   232410   406652
1         6035     66  2020-05-08  10:02:14     Si     YUR  -232410   441379
2         6035     66  2020-05-08  10:02:14     Si     FIZ   232410   406652
3         6035     66  2020-05-08  10:02:14     Si     YUR  -232410   441379
4         6035     67  2020-05-08  10:06:45     Si     FIZ   239213   407318
...        ...    ...         ...       ...    ...     ...      ...      ...
617223    6926    126  2023-11-13  14:45:00     Si     YUR   111037  3202662
617224    6926    127  2023-11-13  14:50:00     Si     FIZ  -117841   456593
617225    6926    127  2023-11-13  14:50:00     Si     YUR   117840  3210182
617226    6926    128  2023-11-13  14:55:00     Si     FIZ  -118417   454632
617227    6926    128  2023-11-13  14:55:00     Si     YUR   118417  3211231

       pos_short pos_long_num pos_short_num              systime
0        -174242         8005          4099  2020-05-08 10:04:31
1        -673789          201           121  2020-05-08 10:04:31
2        -174242         8005          4099  2020-05-08 10:04:31
3        -673789          201           121  2020-05-08 10:04:31
4        -168105         8016          4238  2020-05-08 10:09:06
...          ...          ...           ...                  ...
617223  -3091625          270           166  2023-11-13 14:45:05
617224   -574434         8138         12746  2023-11-13 14:50:06
617225  -3092342          268           168  2023-11-13 14:50:06
617226   -573049         8087         12787  2023-11-13 14:55:05
617227  -3092814          269           168  2023-11-13 14:55:05

[617228 rows x 12 columns]
Файл 'si_full_date.csv' не существует.
2020-05-08
2020-05-09
2020-05-10
2020-05-11
2020-05-12
2020-05-13
2020-05-14
2020-05-15
2020-05-16
2020-05-17
2020-05-18
2020-05-19
2020-05-20
2020-05-21
2020-05-22
2020-05-23
2020-05-24
2020-05-25
2020-05-26
2020-05-27
2020-05-28
2020-05-29
2020-05-30
2020-05-31
2020-06-01
2020-06-02
2020-06-03
2020-06-04
2020-06-05
2020-06-06
2020-06-07
2020-06-08
2020-06-09
2020-06-10
2020-06-11
2020-06-12
2020-06-13
2020-06-14
2020-06-15
2020-06-16
2020-06-17
2020-06-18
2020-06-19
2020-06-20
2020-06-21
2020-06-22
2020-06-23
2020-06-24
2020-06-25
2020-06-26
2020-06-27
2020-06-28
2020-06-29